"""
IRN (Invoice Reference Number) entity model — Contract v1.0.0.

Represents an e-invoice IRN generated by the Invoice Registration Portal (IRP),
linking an invoice to its cryptographically signed payload.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .enums import DocumentType, IRNStatus


class IRN(BaseModel):
    """
    Canonical schema for the IRN entity.

    The IRN is a 64-character hash uniquely identifying an e-invoice.
    It links back to the source invoice and carries the IRP
    acknowledgement metadata.
    """

    model_config = ConfigDict(
        populate_by_name=True,
        str_strip_whitespace=True,
        json_schema_extra={
            "entity": "IRN",
            "contract_version": "1.0.0",
        },
    )

    irn: str = Field(
        ...,
        alias="irn",
        min_length=64,
        max_length=64,
        description="64-character IRN hash",
    )

    irn_date: datetime = Field(
        ...,
        alias="irnDate",
        description="Timestamp when the IRN was generated",
    )

    irn_status: IRNStatus = Field(
        ...,
        alias="irnStatus",
        description="Current status of the IRN (ACTIVE / CANCELLED)",
    )

    invoice_number: str = Field(
        ...,
        alias="invoiceNumber",
        min_length=1,
        max_length=50,
        description="Invoice number linked to this IRN",
    )

    supplier_gstin: str = Field(
        ...,
        alias="supplierGstin",
        min_length=15,
        max_length=15,
        pattern=r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$",
        description="Supplier GSTIN",
    )

    document_type: DocumentType = Field(
        ...,
        alias="documentType",
        description="Document type — INV, CRN, or DBN",
    )

    signed_invoice: Optional[str] = Field(
        None,
        alias="signedInvoice",
        description="Signed JSON payload of the invoice",
    )

    signed_qr_code: Optional[str] = Field(
        None,
        alias="signedQrCode",
        description="Signed QR code data",
    )

    ack_number: str = Field(
        ...,
        alias="ackNumber",
        min_length=1,
        max_length=50,
        description="IRP acknowledgement number",
    )

    ack_date: datetime = Field(
        ...,
        alias="ackDate",
        description="IRP acknowledgement timestamp",
    )

    cancellation_date: Optional[datetime] = Field(
        None,
        alias="cancellationDate",
        description="Timestamp of IRN cancellation, if applicable",
    )

    cancellation_reason: Optional[str] = Field(
        None,
        alias="cancellationReason",
        max_length=500,
        description="Reason for IRN cancellation",
    )
